### PR TITLE
AppVeyor config for mingw

### PR DESCRIPTION
**Pull request by maksbotan**
Hi. I finally got time to do this :)

I decided it'd be cleaner to create separate appveor.yml file for mingw: `appveyor-mingw.yml`. You'll need to create new configuration and specify this file. See the results here:
https://ci.appveyor.com/project/maksbotan/bigartm/build/16

### CODE REVIEW

**Comment by maksbotan** [comment]
We have one more thing to decide. Right now compiling generates a lot of warnings like this:

`warning C4275: non dll-interface class 'google::protobuf::Message' used as base for dll-interface class 'artm::TopTokensScore'`

This happens because we are using static libprofobuf.a, but dllexport the generated types (this is required so that consumers can link to our C++ interface). There are two ways to fix this:

- Export protobuf symbols as well (I believe I can do this easily)
- Suppress the warning with `cl.exe` option

I'd prefer the first way, because sometimes consumers will need to call some message's method that is defined in the base class.

**Comment by ofrei** [comment]
Thanks! I'll create new appveyor configuration (after merging the PR). Great to see all info about tests in Appveyor build!

As for warnings, I agree - it sounds important to fit. Protobuf base classes have LIBPROTOBUF_EXPORT definition, but I'm not sure if this will be enough or if there is something else to make it work.

**Comment by maksbotan** [comment]
I'll try to fix it in the next few days. Please don't merge the PR yet.

**Comment by ofrei** [comment]
@maksbotan this slipped out of my hands, but now is a good time to finish :) I can fix warnings myself. Unless you have some further comments I'll probably merge this tomorrow through my rebased PR (https://github.com/bigartm/bigartm/pull/868).

Thanks again for your contribution! CI for mingw and mingw support itself is very very nice to have in place.

**Comment by maksbotan** [comment]
Hi!
Unfortunately, I also didn't have the time to finish this.

As far as I remember, there remain some errors while compiling with MinGW (right now AppVeyour reports failure for this PR). Please give me some time to fix this.

**Comment by ofrei** [comment]
Fixed long time ago

**Pull request closed without merging**
