### PR TITLE
add script for creating cooc files from batches + minor fixes

### PR DESCRIPTION
**Pull request by MelLain**

### CODE REVIEW

**Comment by MelLain** [comment]
This file can be used for testing (.txt -> .py)
[test.txt](https://github.com/bigartm/bigartm/files/316050/test.txt)

**Comment by sashafrey** [comment]
@MelLain I trust you that it runs - I'm sure you've tested it on your machine)
As for where to put this script, I think it should go into ``python/artm/utility`` (new folder under ``python/artm``).
Also, I think this small pull request should wait until we merge #597 (pip install support), because it is a big change and it would be harder to fix merges if @JeanPaulShapo also changed ``.gitignore`` and ``api.py``.

**Comment by JeanPaulShapo** [comment]
@sashafrey Yes, I've changed `api.py`.

**Comment by MelLain** [comment]
No problems, if this work will be done soon (2-3 days), because after that we strongly need new release with biterms, script for them and relative regularization.

16.06.2016, 22:18, "sashafrey" <notifications@github.com>:

**Pull request merged**
