### PR TITLE
Auto-generate C++-headers and sources from Proto-files

### PR DESCRIPTION
**Pull request by JeanPaulShapo**
Overview of changes are contained in commits' names.
It includes usage of ${PROTOBUF_PROTOC_EXECUTABLE} in CMakeLists, so I strongly recommend someone with Windows to check these changes (maybe @sashafrey or @MelLain?)
On my laptop wth Fedora 22 and no system protobuf distibution it works perfectly.

### CODE REVIEW

**Comment by JeanPaulShapo** [comment]
Seems Travis has CMake 2.8.7 whether new feature of `add_library` available starting from CMake 2.8.8 :(

**Comment by sashafrey** [comment]
Wow.. this is quite unfortunate! My biggest pain with travis so far was
that they are using 12.04 Ubuntu, which comes with very old boost, gcc and
clang. As a result I couldn't use any C++ async features -- neither from
boost, nor from the standard.

I'll let you know if I have any ideas on how to fix this!

On Mon, Mar 14, 2016 at 8:36 PM, Nikita Shapovalov <notifications@github.com

**Comment by JeanPaulShapo** [comment]
@sashafrey Seems I coped with this problem :) Now it passed Travis CI :)

**Comment by JeanPaulShapo** [comment]
Fixed part of #393 (autogenerating)

**Comment by sashafrey** [comment]
@JeanPaulShapo Sorry, I still had no chance to verify weather this works for Windows. I'm still on it and will verify as soon as I can.

**Comment by JeanPaulShapo** [comment]
@sashafrey OK, I see.

**Comment by sashafrey** [comment]
@JeanPaulShapo It works like a charm, also on Windows! I've tested on my machine and also on the build server in EC2 (the one I'm using to generate bigartm releases for windows). Good you haven't change the location of generated messages.pb.[h,cc] --- it imply that my dummy build scripts still can pick these files and add them to the final package.

My only comment would be about ``python/artm/wrapper/messages_pb2.py``. What do we do with this file? If we do nothing I"m sure we will forget to re-generate it.

**Comment by sashafrey** [comment]
@JeanPaulShapo As for the `split messages.proto` part of #393, I suggest we don't do it right now and postpone until `v0.9.0`. Currently some people generate their own classes from `messages.proto` (at least C#, maybe also Java). We should clearly communicate our plan for splitting `messages.proto` before we do this. And currently we have no clear plan, just a vague idea...

The auto-generate part is great, and it would be awesome to include it asap. I'm really sick of manually re-generating all messages each time I do ``git rebase`` :)

**Comment by JeanPaulShapo** [comment]
@sashafrey I need some time to think about `python/artm/wrapper/messages_pb2.py`. I response asap.

**Comment by JeanPaulShapo** [comment]
@sashafrey By the way, could you explain why `messages_pb2.py` put into `python/artm/wrapper` folder rather than into `python/artm` folder?

**Comment by sashafrey** [comment]
@JeanPaulShapo No idea... @MelLain , @romovpa ?

**Comment by JeanPaulShapo** [comment]
@sashafrey I added generating python protobuf messages. This is basic version and now it's strongly depends on generated 'protoc'. Again, I strongly recommend someone with Windows to check these changes :)

**Comment by sashafrey** [comment]
@JeanPaulShapo Sorry, I was slow again... The script (``python setup.py build && python setup.py install``) works, e.g. it generates ``messages.py2``. Here is the output:
```
G:\Users\Alexander\Documents\GitHub\bigartm\python>python setup.py build
running build
Generating ./artm/wrapper/messages_pb2.py...
running build_py
creating build
creating build\lib
creating build\lib\artm
copying artm\batches_utils.py -> build\lib\artm
copying artm\master_component.py -> build\lib\artm
copying artm\model.py -> build\lib\artm
copying artm\regularizers.py -> build\lib\artm
copying artm\scores.py -> build\lib\artm
copying artm\score_tracker.py -> build\lib\artm
copying artm\__init__.py -> build\lib\artm
creating build\lib\artm\wrapper
copying artm\wrapper\api.py -> build\lib\artm\wrapper
copying artm\wrapper\constants.py -> build\lib\artm\wrapper
copying artm\wrapper\exceptions.py -> build\lib\artm\wrapper
copying artm\wrapper\messages_pb2.py -> build\lib\artm\wrapper
copying artm\wrapper\spec.py -> build\lib\artm\wrapper
copying artm\wrapper\utils.py -> build\lib\artm\wrapper
copying artm\wrapper\__init__.py -> build\lib\artm\wrapper

G:\Users\Alexander\Documents\GitHub\bigartm\python>python setup.py install
running install
running bdist_egg
running egg_info
creating bigartm.egg-info
writing requirements to bigartm.egg-info\requires.txt
writing bigartm.egg-info\PKG-INFO
writing top-level names to bigartm.egg-info\top_level.txt
writing dependency_links to bigartm.egg-info\dependency_links.txt
writing manifest file 'bigartm.egg-info\SOURCES.txt'
reading manifest file 'bigartm.egg-info\SOURCES.txt'
writing manifest file 'bigartm.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\artm
copying build\lib\artm\batches_utils.py -> build\bdist.win-amd64\egg\artm
copying build\lib\artm\master_component.py -> build\bdist.win-amd64\egg\artm
copying build\lib\artm\model.py -> build\bdist.win-amd64\egg\artm
copying build\lib\artm\regularizers.py -> build\bdist.win-amd64\egg\artm
copying build\lib\artm\scores.py -> build\bdist.win-amd64\egg\artm
copying build\lib\artm\score_tracker.py -> build\bdist.win-amd64\egg\artm
creating build\bdist.win-amd64\egg\artm\wrapper
copying build\lib\artm\wrapper\api.py -> build\bdist.win-amd64\egg\artm\wrapper
copying build\lib\artm\wrapper\constants.py -> build\bdist.win-amd64\egg\artm\wrapper
copying build\lib\artm\wrapper\exceptions.py -> build\bdist.win-amd64\egg\artm\wrapper
copying build\lib\artm\wrapper\messages_pb2.py -> build\bdist.win-amd64\egg\artm\wrapper
copying build\lib\artm\wrapper\spec.py -> build\bdist.win-amd64\egg\artm\wrapper
copying build\lib\artm\wrapper\utils.py -> build\bdist.win-amd64\egg\artm\wrapper
copying build\lib\artm\wrapper\__init__.py -> build\bdist.win-amd64\egg\artm\wrapper
copying build\lib\artm\__init__.py -> build\bdist.win-amd64\egg\artm
byte-compiling build\bdist.win-amd64\egg\artm\batches_utils.py to batches_utils.pyc
byte-compiling build\bdist.win-amd64\egg\artm\master_component.py to master_component.pyc
byte-compiling build\bdist.win-amd64\egg\artm\model.py to model.pyc
byte-compiling build\bdist.win-amd64\egg\artm\regularizers.py to regularizers.pyc
byte-compiling build\bdist.win-amd64\egg\artm\scores.py to scores.pyc
byte-compiling build\bdist.win-amd64\egg\artm\score_tracker.py to score_tracker.pyc
byte-compiling build\bdist.win-amd64\egg\artm\wrapper\api.py to api.pyc
byte-compiling build\bdist.win-amd64\egg\artm\wrapper\constants.py to constants.pyc
byte-compiling build\bdist.win-amd64\egg\artm\wrapper\exceptions.py to exceptions.pyc
byte-compiling build\bdist.win-amd64\egg\artm\wrapper\messages_pb2.py to messages_pb2.pyc
byte-compiling build\bdist.win-amd64\egg\artm\wrapper\spec.py to spec.pyc
byte-compiling build\bdist.win-amd64\egg\artm\wrapper\utils.py to utils.pyc
byte-compiling build\bdist.win-amd64\egg\artm\wrapper\__init__.py to __init__.pyc
byte-compiling build\bdist.win-amd64\egg\artm\__init__.py to __init__.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying bigartm.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying bigartm.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying bigartm.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying bigartm.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying bigartm.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\bigartm-0.7.4-py2.7.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing bigartm-0.7.4-py2.7.egg
Copying bigartm-0.7.4-py2.7.egg to c:\anaconda\lib\site-packages
Adding bigartm 0.7.4 to easy-install.pth file

Installed c:\anaconda\lib\site-packages\bigartm-0.7.4-py2.7.egg
Processing dependencies for bigartm==0.7.4
Searching for numpy==1.9.2
Best match: numpy 1.9.2
Adding numpy 1.9.2 to easy-install.pth file

Using c:\anaconda\lib\site-packages
Searching for pandas==0.16.2
Best match: pandas 0.16.2
Adding pandas 0.16.2 to easy-install.pth file

Using c:\anaconda\lib\site-packages
Searching for pytz==2015.4
Best match: pytz 2015.4
Adding pytz 2015.4 to easy-install.pth file

Using c:\anaconda\lib\site-packages
Searching for python-dateutil==2.4.2
Best match: python-dateutil 2.4.2
Adding python-dateutil 2.4.2 to easy-install.pth file

Using c:\anaconda\lib\site-packages
Searching for six==1.9.0
Best match: six 1.9.0
Adding six 1.9.0 to easy-install.pth file

Using c:\anaconda\lib\site-packages
Finished processing dependencies for bigartm==0.7.4
```
However, I have to admit that I don't understand how this works and what it does. At least I'm not using the the `build/lib` folder -- my `PYTHON_PATH` refers directly to `python/artm/wrapper` folder (the one under git source control). Personally I don't think it is sufficient to generate messages.pb2 as part of python setup, and I would rather prefer to add this into CMakeLists, and output messages.pb2 file into `python/artm/wrapper/` (e.g. to the folder where it was previously).

I suggest we discuss this on Skype to find most practical solution for users and developers :)

**Comment by sashafrey** [comment]
:+1:

**Pull request merged**
