### PR TITLE
Sphinx python docs

### PR DESCRIPTION
**Pull request by JeanPaulShapo**
This pull request introduces basic functionality of generating Python API documentation automatically, using docstrings. Feel free to comment and suggest new ideas before merge :)

Unfortunately I didn't manage to create pull request against `stable` branch, because I created my branch from `master` and couldn't merge commits on `master_component.py` :-(

### CODE REVIEW

**Comment by JeanPaulShapo** [comment]
@sashafrey I recommend you to check commits and merge if possible.

**Comment by sashafrey** [comment]
@JeanPaulShapo Thanks! This commit is now online at http://docs.bigartm.org/en/master/ .
I'll cherry-pick the changes to `stable` branch when we fix documentation for `model.py`. After all `model.py` is what most people use, so I don't want to confuse them by providing documentation to `master_component.py`.
@MelLain Could you cleanup comments in model.py to make it build with documentation?

**Comment by sashafrey** [comment]
@JeanPaulShapo Hm.. I see documentation locally on my machine, however online version looks empty:
http://docs.bigartm.org/en/master/python_interface/master_component.html

**Comment by JeanPaulShapo** [comment]
@sashafrey It requires `pandas` to load `artm` library

**Comment by sashafrey** [comment]
Sounds reasonable.. Do you have an account at readthedocs? I can add you to mainteiners there, to give access to https://readthedocs.org/dashboard/bigartm/edit/

**Comment by JeanPaulShapo** [comment]
@sashafrey Now I have) ***JeanPaulShapo***

**Comment by sashafrey** [comment]
Done :) Check the link above

**Comment by sashafrey** [comment]
http://docs.readthedocs.org/en/latest/faq.html#my-project-isn-t-building-with-autodoc
```
First, you should check out the Builds tab of your project. That records all of the build attempts that RTD has made to build your project. If you see ImportError messages for custom Python modules, you should enable the virtualenv feature in the Admin page of your project, which will install your project into a virtualenv, and allow you to specify a requirements.txt file for your project.
```

I can't see ImportError on build tab.

**Comment by JeanPaulShapo** [comment]
You can open latest master build, the open the last `python` command and see `ImportError` in output

**Comment by sashafrey** [comment]
Ah, now I see. I didn't realize that those thingies at the build page are buttons that I can click :)

**Comment by sashafrey** [comment]
Could you fix this?

>enable the virtualenv feature in the Admin page of your project, which will install your project into a virtualenv, and allow you to specify a requirements.txt file for your project.

**Comment by JeanPaulShapo** [comment]
@sashafrey seems I made it, now I'm waiting for build status

**Comment by JeanPaulShapo** [comment]
@sashafrey what branch tag 'latest' points to?

**Comment by JeanPaulShapo** [comment]
Oh, it needs 'google.protobuf' also. I'll try to resolve the issue ASAP.

**Comment by sashafrey** [comment]
'latest' points to 'master'. Thanks! I'll leave it to you then :)
Also if you see issues in `stable` branch after this just feel free to add `docs/requirements.txt` or any other files into the `stable` branch.

**Comment by JeanPaulShapo** [comment]
@sashafrey It works!

We have `numpy`, `pandas` and `google.protobuf` as internal dependencies
* `numpy` and `pandas`  were easily mocked by object `autodoc_mock_imports` in `docs/conf.py`.
*  I didn't manage to mock 'google.protobuf', that's why I decided to install protobuf==2.6.1 using
`requirements.txt`. It works, so we may assume BigARTM works with protobuf==2.6.1 on Linux
* Additionally, we may try to use some features of Sphinx to avoid reformatting docstrings radically.
I regret to waste about an hour reformatting `master_component.py` manually (

**Comment by JeanPaulShapo** [comment]
Fixed `stable` branch by #469

**Comment by sashafrey** [comment]
@JeanPaulShapo Great! I'm absolutely happy to see this docs online!
I'll take it from here and fix other APIs, and also follow up on the actual content of the documentation.

Do you see any chance of generating docs from ``messages.proto`` file?

**Comment by JeanPaulShapo** [comment]
@sashafrey Right now I don't know how to do it. I'll explore Sphinx documentation.

**Comment by sashafrey** [comment]
@JeanPaulShapo Thanks! But don't spend too much time on it, I was just curious. In `model.py` we are hiding all protobuf messages quite well, so most users don't have to care about protobuf messages. The important onces, like `batch` or `item`, we can document separately.

**Pull request merged**
