### PR TITLE
TopicSelectionTheta regularizer fixes

### LINKED ISSUE #580: Failed test_regularizer_topic_selection.py test: assert 7 == 9
I came across with this problem when trying to enable GCC 4.9 support on Travis CI: see PR #579. 
Now I have at least three machines with these problems (I use `master` branch with last commit 2254dc0e08bb83bf37dc6eed19ff926d06f7a147):
* my local machine (*Fedora 22*)
* Travis CI *trusty* image (*Ubuntu 14.04.3 LTS*, [failed build](https://travis-ci.org/bigartm/bigartm/builds/136090387))
* AWS machine (*Ubuntu 14.04.4 LTS*)

Surprisingly, testing on Travis CI *precise* image works **well** (*Ubuntu 12.04.5 LTS*, [successfull build](https://travis-ci.org/bigartm/bigartm/builds/136051003))

@sashafrey @MelLain 
Can we guarantee that we start from the same matrices Phi and Theta on every machine?
Any other ideas?

### PR DESCRIPTION
**Pull request by JeanPaulShapo**
Fixes #580.
The main change in `python/artm/artm_model.py` file (I believe it was a bug), other changes are "cosmetic" and related to unit testing and typo fixes.

### CODE REVIEW

**Comment by JeanPaulShapo** [comment]
@sashafrey @MelLain Is it possible to run Python API tests on your local machines to verify this PR?

**Comment by ofrei** [comment]
@JeanPaulShapo Thanks! Sure, I'll test on my machine later today.

**Comment by ofrei** [comment]
@JeanPaulShapo Sorry, I spent more than 1 hour yesterday trying to run these tests on windows, but I failed to do so. It is too messy - the test can't find the data, then it can't create the folder (crashes in native code from boost::create_directory). I'll try on clean machine, but in the meantime maybe someone else can run the tests? @MelLain do you have issues running python tests on windows?

**Comment by ofrei** [comment]
I've tested this on windows and everything works well. To fix my issues I've created a ``BIGARTM_UNITTEST_DATA`` env. variable -- see my pr. #612 . Is this OK? I'll have to set it on Linux as well, to run the tests.

**Comment by JeanPaulShapo** [comment]
@sashafrey Yes, It's absolutely OK. Moreover, it provides more flexibility.

**Comment by ofrei** [comment]
@JeanPaulShapo Please rebase the PR to ``bigartm/master``. I think this will trigger both travis and appveyor.

**Comment by JeanPaulShapo** [comment]
@ofrei Is it OK now to merge after checking on travis and appveyor?

**Comment by ofrei** [comment]
@JeanPaulShapo Yep, thanks for fixing this!

**Pull request merged**
