### PR TITLE
Packing windows releases as appveyor artifacts

### PR DESCRIPTION
**Pull request by ofrei**

### CODE REVIEW

**Comment by JeanPaulShapo** [comment]
@ofrei Maybe there are some problems with parallel execution and generating from *.proto source?

**Comment by ofrei** [comment]
@JeanPaulShapo Good suggestion. I've disabled parallel, let's see if it helps. I'm guessing this is just memory limitation that make compiler crash on our huge headers generated from messages.proto.

**Comment by JeanPaulShapo** [comment]
@ofrei Look [here](https://ci.appveyor.com/project/bigartm/bigartm/build/22#L9685)

**Comment by JeanPaulShapo** [comment]
@ofrei I see two problems:
* parallel build sometimes doesn't work properly (problem related to dependencies relationship in `*/CMakeLists.txt`)
* Retrieving KOS dataset in platform-independent way

Do you need help?

**Comment by ofrei** [comment]
@JeanPaulShapo Not really.. For now I'll play a bit more myself. But I'll let you know about any important issues that I won't have time to fix myself.

**Comment by ofrei** [comment]
The goal of this pull request is to automatically generate BigARTM release package from each appveyor build. This works, and the latest build from master can be download by this permanent link:

https://ci.appveyor.com/api/projects/bigartm/bigartm/artifacts/BigARTM.7z?branch=master

There are many other things to improve here, but for now I consider myself done with appveyor.

**Pull request merged**
