### PR TITLE
Error in pPMI formula fixing

### PR DESCRIPTION
**Pull request by Angriff**

### CODE REVIEW

**Comment by JeanPaulShapo** [comment]
@Angriff Does this PR reflects intended changes?

**Comment by Angriff** [comment]
@JeanPaulShapo MMM, what means *intended*?

**Comment by JeanPaulShapo** [comment]
@Angriff It was some vague question. I'll make another try: Is it OK to merge this PR after passing status checks? Have we lost any significant commits after some tricks with local and remote branches?

**Comment by Angriff** [comment]
@JeanPaulShapo Yes, we can merge PR after passing status checks.  We will not lost any significant commits.

**Comment by JeanPaulShapo** [comment]
👍

**Pull request merged**
