### PR TITLE
fixing error in pPMI formula in documentation of coherence score

### PR DESCRIPTION
**Pull request by Angriff**

### CODE REVIEW

**Comment by JeanPaulShapo** [comment]
@Angriff rebase with origin master?

**Comment by Angriff** [comment]
Can you help me with git... I have following message after `git rebase upstream/master`:

``` First, rewinding head to replay your work on top of it...
Applying: Misspelling fix: 'inpretabilty'->'intepretability'
Using index info to reconstruct a base tree...
M	docs/tutorials/scores_descr.txt
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
Applying: Documentation page about coocurancy and coherence is added
Using index info to reconstruct a base tree...
M	docs/tutorials/python_userguide/coherence.txt
.git/rebase-apply/patch:27: trailing whitespace.
* pointwise PMI: :math:`value(u,v)=\left[\log\cfrac{n(u,v)}{n(u)n(v)}\right]_{+}`, 
.git/rebase-apply/patch:34: trailing whitespace.
Let's assume you have file `cooc.txt` with coocurancies of tokens. Also you should have vocabulary file in UCI format `vocab.txt` corresponding to `cooc.txt` file. 
.git/rebase-apply/patch:45: trailing whitespace.
Where 
.git/rebase-apply/patch:57: trailing whitespace.
	                            class_id='@default_class', 
.git/rebase-apply/patch:58: trailing whitespace.
	                            num_tokens=10, 
warning: 5 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging docs/tutorials/python_userguide/coherence.txt
CONFLICT (content): Merge conflict in docs/tutorials/python_userguide/coherence.txt
error: Failed to merge in the changes.
Patch failed at 0002 Documentation page about coocurancy and coherence is added
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```
I am afraid to break the repo... `git mergetool` shows 2 version of *coherence.txt* file, but both are not the last version...

**Comment by JeanPaulShapo** [comment]
@Angriff I think, it'll be better to avoid some unnecessary commits. You can do smth like this:
``git checkout -b fix_docs upstream/master``
``git cherry-pick a265e71 # the only significant commit``
In that case you'll have the only commit applied at top of master. After that, you may refresh remote branch and PR via ``git push origin Docs``

**Comment by Angriff** [comment]
Is it still actual? I've merged master into 'Docs' via web UI of github...
If yes, so should I push with `git push origin Docs` or `git push origin fix_docs`?

**Comment by JeanPaulShapo** [comment]
@Angriff Becase your branch still has the commit I've mentioned above, it's OK to do. It's also OK to push with ``git push origin Docs``, because remote repo doesn't track names of your local branches. In that case we'll lose all unnecessary commits in this PR.

**Comment by Angriff** [comment]
Hmmmm.... Result of `git push origin Docs`:
```To git@github.com:Angriff/bigartm.git
 ! [rejected]        Docs -> Docs (fetch first)
error: failed to push some refs to 'git@github.com:Angriff/bigartm.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details```

**Comment by JeanPaulShapo** [comment]
@Angriff Yes. Add ``--force`` flag: ``git push --force origin Docs``

**Comment by Angriff** [comment]
Done! Should I resolve conflicts via UI on github?

**Comment by JeanPaulShapo** [comment]
@Angriff Hmm... have you made checkout from ``upsteam\master``?

**Comment by Angriff** [comment]
@JeanPaulShapo  Yes. Exactly as you wrote....
```
git checkout -b fix_docs upstream/master
git cherry-pick a265e71
git push --force origin Docs
```

**Comment by JeanPaulShapo** [comment]
@Angriff OK, I suppose ``upstream`` points to original bigartm repo. Could you check whether it's true or not (i.e. examine output of ``git remote -v`` and find URL corresponding to ``upstream``)? Try to perform all the steps again, but now make ``git fetch upstream`` (and of course remove branch ``fix_docs`` beforehand: ``git checkout Docs && git branch -D fix_docs``)

**Comment by JeanPaulShapo** [comment]
@Angriff Sorry, I'm wrong with name of the branch - remote version of ``Docs`` corresponds to local ``Docs``. So you need to push with ``git push origin fix_docs`` instead of ``git push origin Docs``

**Comment by Angriff** [comment]
@JeanPaulShapo So, that pull-request will be closed, right? And I should create another one with `fix_docs` branch?

**Comment by JeanPaulShapo** [comment]
@Angriff Right. Sorry again for this bullshit.

**Comment by Angriff** [comment]
@JeanPaulShapo Sorry for dummy question: what is the right way to push new changes? For every pack of edits  - separate branch and pull request? How should I manage branches in my forked repo (not original)?

**Comment by JeanPaulShapo** [comment]
@Angriff 
Short answer: it depends, but in my opinion you should integrate changes from base branch (e.g. ``upstream/master``) into your local branch before doing some stuff (of course, when it's possible).
Long answer: I think It'll be better to discuss it personally somewhere.

**Pull request closed without merging**
