### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by JeanPaulShapo**

### CODE REVIEW

**Comment by sashafrey** [comment]
Changes look ok. Could you please make a new pull request with clean history? I suggest to checkout bigartm/master and cherry-pick two commits:
* https://github.com/JeanPaulShapo/bigartm/commit/aa81113b775831494143547aaa70da303b67a133
* 
https://github.com/JeanPaulShapo/bigartm/commit/370335cfbd98833a2a401d1d0b20a7ce03d58853
Other changes appears to  be in ``bigartm/master``, including fixed bug in calculating phi sparsity.

**Comment by JeanPaulShapo** [comment]
@sashafrey Ok, I'll try it. Do you create pull requests in the same manner (using cherry-pick)?

**Comment by JeanPaulShapo** [comment]
Opened new pull request: https://github.com/bigartm/bigartm/pull/338

**Comment by sashafrey** [comment]
@JeanPaulShapo No, I fix my branch... :) Have you tried [add git remote](https://help.github.com/articles/adding-a-remote/), delete your local master, and recreate it from ``bigartm/master``? You can do it as follows:

```
git remote add bigartm https://github.com/bigartm/bigartm.git
git fetch bigartm
git branch -D master
git checkout bigartm/master
git checkout -b master
```

Then if you create a pull request from your master it will be clean.

To update your master I strongly suggest avoid ``git merge``. Use ``git rebase bigartm/master`` to pull latest changes into your branch.

**Comment by JeanPaulShapo** [comment]
@sashafrey Thanks, got it! Anyway, clean pull request is still open: https://github.com/bigartm/bigartm/pull/338

**Comment by sashafrey** [comment]
@JeanPaulShapo This is now merge.
Out of curiosity, why you moved the code out from `BatchVectorizer` construct into a separate method? In C++ it is perfectly fine to throw exceptions from within constructor.

**Comment by JeanPaulShapo** [comment]
@sashafrey Yes, we can throw exceptions from within constructor. However, in that case destructor won't be called, and we will never delete batch folder. 
I came across this problem while reproducting the bug.

**Comment by sashafrey** [comment]
@JeanPaulShapo Ah, right... Yes, good catch! Thank you for fixing this.

**Pull request closed without merging**
