### PR TITLE
ArtmDuplicateMasterComponent (deep copy)

### PR DESCRIPTION
**Pull request by sashafrey**
Implement deep copy functionality for `MasterComponent`. Certain things are deliberately missing:
- old-style models are not copied
- theta matrix cache is not copied
- score values are not copied

Certain tricks involved in this operation:
- copying of an Attached matrix result in an ordinary (not attached) matrix
- dictionaries, scores (configs) and regularizers (configs) are copied

### CODE REVIEW

**Comment by romovpa** [comment]
add the new call to the `python/artm/wrapper/spec.py`:

```python
    CallSpec(
        'ArtmDuplicateMasterComponent',
        [('master_id', int), ('args', messages.DuplicateMasterComponentArgs)],
    ),
```

**Comment by sashafrey** [comment]
`ArtmDuplicateMasterComponent` returns new `master_id`, so call spec should be
```
        'ArtmDuplicateMasterComponent',
        [('master_id', int), ('config', messages.DuplicateMasterComponentArgs)],
        result=ctypes.c_int,
```

Bwt, I've added another cool feature, which allows to retrieve usage info from MasterComponent. Apologies for sneaking it into this pull request --- this is because I was eager to use this feature to write better C++ tests for `ArtmDuplicateMasterComponent` functionality.

If you are interested in what's included in `HealthInfo` message, take a look at the change in `messages.proto`. Output looks somewhat similar to this:
```
master_id: 2
config {
  processors_count: 2
  processor_queue_max_size: 2
}
score {
  name: "PerplexityScore:urn:uuid:03ea30e1-4c37-11e5-8d23-00268333e0e1"
  type: "class artm::score::Perplexity"
}
score {
  name: "TopTokensScore:urn:uuid:03ea57f0-4c37-11e5-8197-00268333e0e1"
  type: "class artm::score::TopTokens"
}
model {
  name: "nwt"
  type: "class artm::core::DensePhiMatrix"
  topics_count: 10
  token_count: 6906
}
model {
  name: "pwt"
  type: "class artm::core::DensePhiMatrix"
  topics_count: 10
  token_count: 6906
}
merger_queue_size: 0
processor_queue_size: 0
```

**Comment by romovpa** [comment]
Why **health** info? =)
Maybe something more clear? E.g. `MasterComponentInfo`, `MasterComponentStatus`

**Comment by romovpa** [comment]
anyway, good features, i'm ok

**Comment by sashafrey** [comment]
I've also started with `MasterComponentInfo`, and at some point rename to `HealthInfo`. I'm not sure I have good arguments except it is a shorter name. Also I didn't like repeating `MasterComponent` in the name of the messages returned by MasterComponent class. Basically, we are using `MasterComponent` as a namespace, and ideally the names just `Info`, `Config` (e.g. MasterComponent::Info, MasterComponent::Config). But these are just random thoughts... Generally I tend to agree that `HealthInfo` is a bit weird.

@MelLain, what do you think?

**Comment by MelLain** [comment]
As for me Info or State looks better

27.08.2015, 08:44, "sashafrey" <notifications@github.com>:

**Comment by sashafrey** [comment]
Rename back to `MasterComponentInfo`

**Pull request merged**
