### PR TITLE
Implement rand-seed switch to bigartm CLI + small code cleanup

### LINKED ISSUE #319: Implement --rand-seed switch to bigartm CLI
According to BigARTM CLI specification we need to support random seed that allows to control initialization of the topic model.

### PR DESCRIPTION
**Pull request by JeanPaulShapo**
Fixed #319

### CODE REVIEW

**Comment by ofrei** [comment]
@JeanPaulShapo I would prefer to rename this switch from ``random-seed`` to just ``seed``.
Currently the default behavior to use time-dependent seed, e.g. different results from run to run.
If user wants to get a deterministic behavior, he should fix a ``seed``. I would use ``random-seed`` in a situation where default behavior is deterministic, and ``--random-seed`` enables time-dependend seed.
Do you agree on this?

**Comment by ofrei** [comment]
@JeanPaulShapo Ah, now I see that the ticket #319 explicitly states in the title that the option should be named ``--random-seed``.  I think this hasn't been planed very well.. Sorry for this.

**Comment by JeanPaulShapo** [comment]
@ofrei You can look into [Russian specification](https://github.com/bigartm/bigartm-book/blob/master/junk/cli/BigARTM_CommandLineInferface.ipynb).

**Comment by ofrei** [comment]
@JeanPaulShapo I see... So we keep ``--random-seed`` then?

**Comment by JeanPaulShapo** [comment]
@ofrei I think yes - we keep `--rand-seed`.

**Comment by ofrei** [comment]
@JeanPaulShapo Agreed! :)

**Comment by ofrei** [comment]
@JeanPaulShapo Forget to mention - it would be nice to mention this change in release notes (https://github.com/bigartm/bigartm/blob/master/docs/release_notes/bigartm_cli.txt).

**Comment by JeanPaulShapo** [comment]
@ofrei Done!

**Pull request merged**
