### PR TITLE
Improve online documentation

### PR DESCRIPTION
**Pull request by JeanPaulShapo**
Main parts:
- make new section 'Installation'
- move Windows and Linux tutorials to legacy pages

However, there is need to fix some broken links later.

### CODE REVIEW

**Comment by JeanPaulShapo** [comment]
Fixed #386

**Comment by JeanPaulShapo** [comment]
Hope it fixed #395

**Comment by sashafrey** [comment]
- Please re-create this pull request against `bigartm/stable` branch, because it is really useful and we would like to publish it immediately.
- Remove `vim:ft=rst` at the end of tutorials/python_api.

**Comment by JeanPaulShapo** [comment]
@sashafrey

**Comment by JeanPaulShapo** [comment]
@sashafrey I wonder why remove `vim:ft=rst` only in tutorials/python_api :)

**Comment by sashafrey** [comment]
@JeanPaulShapo I haven't noticed it in other places :)

**Comment by JeanPaulShapo** [comment]
@sashafrey Ok, I fix it in the next commit.

**Comment by sashafrey** [comment]
@JeanPaulShapo I've added you to commiters group, so feel free to merge your pull request for documentations. Please, create them against `bigartm/stable` branch because this is the default branch that show up at http://docs.bigartm.org. I will regularly merge `bigartm/stable` into `bigartm/master`.

**Comment by sashafrey** [comment]
For the code I'd still prefer to review and discuss changes, but for documentation I think its OK to just merge. Documentation is now in such a bad state that any change will improve it :) So I fully trust you on this! :)

**Comment by JeanPaulShapo** [comment]
@sashafrey Is it OK not only merge 'documentaton' pull requests but also close 'documentation' issues related to these pull requests?

**Comment by sashafrey** [comment]
@JeanPaulShapo yes, sure!

**Pull request closed without merging**
