### PR TITLE
Enable installing python interface on Unix systems via 'make install'

### PR DESCRIPTION
**Pull request by JeanPaulShapo**
This pull request solves #70. In particular, now it implements all steps that 'make install' should produce now. These changes work well on my laptop with Fedora 21 and Amazon instance with Ubuntu 14.04 LTS. Question and comments are welcome. Also, feel free to comment if it does't work
on your Linux machine.

### CODE REVIEW

**Comment by sashafrey** [comment]
Great job, thanks! My linux machine is also an Ubuntu 14.04 on Amazon, so I'm sure it will work too :)
This pull request is only concerned about python API and its python dependencies, correct? I think we also need to install artm.so and make sure that python API is able to find it. Then python story would be complete, and user can simply delete bigartm build folder after `make install` and python API will stll work.

It would be also great to install bigartm (a CLI executable).

**Comment by JeanPaulShapo** [comment]
@sashafrey Ok, I see it's better to describe what steps 'make install' performs according to this pull request:
0. During 'make' step, 'python setup.py build' both for bigartm package and protobuf package are executed (using auxiliary targets python_build and python_protobuf_build), also protoc executable is copied to 3rdparty/protobuf/src/
1. First of all, it installs protobuf 2.5.1-pre via 'python setup.py install'
2. Next, it installs libartm.so and bigartm into appropriate directories (${PREF}/lib and ${PREF}/bin, where ${PREF} is root directory for install)
3. In the end, it installs bigartm-0.7.3 (current version of bigartm) via 'python setup.py install'.

**Comment by JeanPaulShapo** [comment]
@sashafrey There is one problem for 'bigartm' python package: unfortunately, I didn't manage to install 'numpy' as dependency (there are some compilation errors only when I install 'numpy' as dependency, not as standalone package). That's why I think it's better to mention somewhere about this problem and force user to install numpy beforehand, either via system package manager or using `pip`.

**Comment by sashafrey** [comment]
For `numpy` dependency - I think it is fully OK to ask user to install it. This is a very common task, and I expect most users already have numpy installed.

The steps that you descripes for `make install` is exactly what I've been looking for, however I don't understand how it works... Which file is responsible for (2) and (3) logic. Is it somewhere in CMakeLists.txt or python.py? I'm sure I'm missing something...

**Comment by JeanPaulShapo** [comment]
@sashafrey 
for installing libartm.so - file src/artm/CMakeLists.txt, line 141
for installing bigartm executable - file src/bigartm/CMakeLists.txt, line 30
for installing 'bigartm' python package - file python/CMakeLists.txt, lines 17-24

**Comment by sashafrey** [comment]
@JeanPaulShapo Ok, I see. I didn't know it was already implemented, so I've tried to search only withing the changes from pull request. Thank you!

**Comment by JeanPaulShapo** [comment]
@sashafrey Is it OK to close issue #70?

**Comment by sashafrey** [comment]
@JeanPaulShapo Yes, thank you!

**Pull request merged**
