### PR TITLE
Start docs refactoring. Rewrite the general structure

### PR DESCRIPTION
**Pull request by MelLain**

### CODE REVIEW

**Comment by JeanPaulShapo** [comment]
@MelLain While building documentation on my local machine, I noted some warnings caused by links from Protobuf messages' description to non-existing API calls (e.g. ArtmRequestLoadDictionary). Do you think it is worth fixing in this PR?

**Comment by JeanPaulShapo** [comment]
@ofrei What do you think about creating separate project for documentation?

**Comment by ofrei** [comment]
@JeanPaulShapo `ArtmRequestLoadDictionary` is minor issue as docs for protobuf messages are outdated anyway.
Separate project - I don't think this is a good idea because by keeping them together we automatically get correct versioning (aligned with git tags in bigartm repo). Just feel free to commit documentation changes whenever you want, you don't need green PR or code review.

@MelLain Everything looks very good!  Just one minor remark - we should use consistent capital letters in the titles. For example now it says "Python Interface" and "C++ interface". I think in titles each word should start with capital letter (except "a", "the", "for", etc.. )

**Comment by ofrei** [comment]
@MelLain Maybe change ``Low-level API in C`` into ``C interface``.

**Comment by ofrei** [comment]
and `Basic usage of BigARTM Python API` into `Python Tutorial` or `Python Guide - Basic`

**Pull request merged**
